# Generated by Django 4.2.8 on 2024-01-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_category_books_book_type'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.books'),
        ),
    ]
