# Generated by Django 4.2.8 on 2024-01-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_balance',
        ),
    ]
