# Generated by Django 4.2.8 on 2024-01-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_account_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='users',
        ),
    ]
