# Generated by Django 4.2.8 on 2024-01-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_account_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='diposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
