# Generated by Django 4.2.8 on 2024-01-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_category_books_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
